### ISSUE TITLE
Style issue

### ISSUE THREAD

**Issue by wong2** [hyperhq/www.hyper.sh#10]
![image](https://cloud.githubusercontent.com/assets/321947/20089819/466dc7a0-a5c4-11e6-9d9f-99aa521fb697.png)

url: https://console.hyper.sh/containers
browser: Chrome 54

**Comment by imeoer** [comment]
Hey @wong2 , what's wrong with this style?

**Comment by wong2** [comment]
@imeoer oh, is it on purpose? I thought it's a bug..
