### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by Gex8** [hyperhq/www.hyper.sh#45]
Hi there,

I know this isn't the right place to ask what is going on, but our containers went down more than one and a half hour ago and I cannot reach hyper.sh forum or anything relevant. I don't get any notification around the service stop. Can you please tell me what is going on?

**Comment by kevinsimper** [comment]
@Gex8 Haven't you gotten the email from Hyper.sh about them shutting down? :) They have send out dozen of them :)

**Comment by Gex8** [comment]
@kevinsimper I've got none of them and I don't know why, because I got emails about the invoices every time...

**Comment by kevinsimper** [comment]
@Gex8 Hope it works out, it was also short notice, only 25 days, https://news.ycombinator.com/item?id=18734658

**Comment by Gex8** [comment]
@kevinsimper Thanks. I've just seen this article... In the meantime, I had a chance to contact the Hyper team, the problem seems to be resolved soon.

**Comment by gnawux** [comment]
The data export issue has been solved. Thanks @kevinsimper for your help and thanks @Gex8 for your patience.
